import { mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = resolve(ROOT, "public");
const SOURCES = [
  "src/00-start.js",
  "src/05-lang-switcher.js",
  "data.js",
  "data-chinese.js",
  "src/10-utils.js",
  "src/20-api.js",
  "src/30-state.js",
  "src/40-dom.js",
  "src/50-tabs.js",
  "src/60-flashcards.js",
  "src/70-reading.js",
  "src/80-grammar.js",
  "src/90-chat.js",
  "src/100-listening.js",
  "src/110-matching.js",
  "src/cn-modules.js",
  "src/120-bootstrap.js",
  "src/999-end.js",
];

async function buildBundle() {
  const parts = [
    "/* Generated by build.mjs. Edit data.js, data-chinese.js and src/*.js instead. */",
    "",
  ];

  for (const relativePath of SOURCES) {
    const sourcePath = resolve(ROOT, relativePath);
    const content = (await readFile(sourcePath, "utf8")).trimEnd();
    parts.push(`// ---- ${relativePath} ----`);
    parts.push(content);
    parts.push("");
  }

  const output = `${parts.join("\n").trimEnd()}\n`;

  await mkdir(PUBLIC_DIR, { recursive: true });
  await writeFile(resolve(ROOT, "script.js"), output, "utf8");
  await writeFile(resolve(PUBLIC_DIR, "script.js"), output, "utf8");
  await copyFile(resolve(ROOT, "index.html"), resolve(PUBLIC_DIR, "index.html"));
  await copyFile(resolve(ROOT, "style.css"), resolve(PUBLIC_DIR, "style.css"));

  console.log("Built script.js and synced public assets");
}

buildBundle().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
