from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parent
PUBLIC_DIR = ROOT / "public"
SOURCES = [
    "src/00-start.js",
    "data.js",
    "src/10-utils.js",
    "src/20-api.js",
    "src/30-state.js",
    "src/40-dom.js",
    "src/50-tabs.js",
    "src/60-flashcards.js",
    "src/70-reading.js",
    "src/80-grammar.js",
    "src/90-chat.js",
    "src/100-listening.js",
    "src/110-matching.js",
    "src/120-bootstrap.js",
    "src/999-end.js",
]


def bundle_content() -> str:
    parts = [
        "/* Generated by build.py. Edit data.js and src/*.js instead. */",
        "",
    ]

    for relative_path in SOURCES:
        source_path = ROOT / relative_path
        content = source_path.read_text(encoding="utf-8").rstrip()
        parts.append(f"// ---- {relative_path} ----")
        parts.append(content)
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def build_bundle() -> None:
    output = bundle_content()
    PUBLIC_DIR.mkdir(exist_ok=True)
    (ROOT / "script.js").write_text(output, encoding="utf-8")
    (PUBLIC_DIR / "script.js").write_text(output, encoding="utf-8")

    for filename in ("index.html", "style.css"):
        shutil.copy2(ROOT / filename, PUBLIC_DIR / filename)


if __name__ == "__main__":
    build_bundle()
    print("Built script.js and synced public assets")
