const defaultChineseData = {
    "1. Động từ Cốt lõi (20 từ)": [
        { zh: "是", vi: "Là, thì", pro: "shì", ex: "我是学生。(Wǒ shì xuésheng - Tôi là học sinh.)" },
        { zh: "有", vi: "Có", pro: "yǒu", ex: "我有一本书。(Wǒ yǒu yī běn shū - Tôi có một quyển sách.)" },
        { zh: "做", vi: "Làm", pro: "zuò", ex: "你在做什么？(Nǐ zài zuò shénme - Bạn đang làm gì?)" },
        { zh: "说", vi: "Nói", pro: "shuō", ex: "请慢慢说。(Qǐng mànmàn shuō - Xin hãy nói chậm thôi.)" },
        { zh: "去", vi: "Đi", pro: "qù", ex: "我们去学校。(Wǒmen qù xuéxiào - Chúng ta đi học.)" },
        { zh: "来", vi: "Đến", pro: "lái", ex: "请进来。(Qǐng jìnlái - Mời vào.)" },
        { zh: "看", vi: "Nhìn, xem", pro: "kàn", ex: "我在看书。(Wǒ zài kàn shū - Tôi đang đọc sách.)" },
        { zh: "吃", vi: "Ăn", pro: "chī", ex: "我想吃饺子。(Wǒ xiǎng chī jiǎozi - Tôi muốn ăn sủi cảo.)" },
        { zh: "喝", vi: "Uống", pro: "hē", ex: "我喝茶。(Wǒ hē chá - Tôi uống trà.)" },
        { zh: "买", vi: "Mua", pro: "mǎi", ex: "我要买苹果。(Wǒ yào mǎi píngguǒ - Tôi muốn mua táo.)" },
        { zh: "学", vi: "Học", pro: "xué", ex: "我学中文。(Wǒ xué zhōngwén - Tôi học tiếng Trung.)" },
        { zh: "知道", vi: "Biết", pro: "zhīdào", ex: "我知道了。(Wǒ zhīdào le - Tôi biết rồi.)" },
        { zh: "想", vi: "Muốn, nghĩ", pro: "xiǎng", ex: "我想去旅游。(Wǒ xiǎng qù lǚyóu - Tôi muốn đi du lịch.)" },
        { zh: "给", vi: "Cho, đưa", pro: "gěi", ex: "给我一杯水。(Gěi wǒ yī bēi shuǐ - Cho tôi một ly nước.)" },
        { zh: "用", vi: "Sử dụng", pro: "yòng", ex: "你用筷子吗？(Nǐ yòng kuàizi ma - Bạn dùng đũa không?)" },
        { zh: "找", vi: "Tìm kiếm", pro: "zhǎo", ex: "我找不到钥匙。(Wǒ zhǎo bú dào yàoshi - Tôi không tìm thấy chìa khóa.)" },
        { zh: "问", vi: "Hỏi", pro: "wèn", ex: "我想问一个问题。(Wǒ xiǎng wèn yī gè wèntí - Tôi muốn hỏi một câu.)" },
        { zh: "回", vi: "Quay về, trả lời", pro: "huí", ex: "我回家了。(Wǒ huí jiā le - Tôi về nhà rồi.)" },
        { zh: "帮", vi: "Giúp đỡ", pro: "bāng", ex: "请帮帮我。(Qǐng bāng bāng wǒ - Xin hãy giúp tôi.)" },
        { zh: "叫", vi: "Gọi, tên là", pro: "jiào", ex: "我叫小明。(Wǒ jiào Xiǎomíng - Tôi tên là Tiểu Minh.)" },
    ],
    "2. Danh từ Quen thuộc (20 từ)": [
        { zh: "时间", vi: "Thời gian", pro: "shíjiān", ex: "没有时间了。(Méiyǒu shíjiān le - Không còn thời gian nữa.)" },
        { zh: "朋友", vi: "Bạn bè", pro: "péngyou", ex: "他是我的好朋友。(Tā shì wǒ de hǎo péngyou - Anh ấy là bạn tốt của tôi.)" },
        { zh: "家", vi: "Nhà, gia đình", pro: "jiā", ex: "我家有三口人。(Wǒ jiā yǒu sān kǒu rén - Nhà tôi có 3 người.)" },
        { zh: "学校", vi: "Trường học", pro: "xuéxiào", ex: "学校很大。(Xuéxiào hěn dà - Trường học rất to.)" },
        { zh: "工作", vi: "Công việc", pro: "gōngzuò", ex: "你的工作怎么样？(Nǐ de gōngzuò zěnmeyàng - Công việc của bạn thế nào?)" },
        { zh: "钱", vi: "Tiền", pro: "qián", ex: "这个多少钱？(Zhège duōshao qián - Cái này bao nhiêu tiền?)" },
        { zh: "手机", vi: "Điện thoại di động", pro: "shǒujī", ex: "我的手机没电了。(Wǒ de shǒujī méi diàn le - Điện thoại tôi hết pin.)" },
        { zh: "水", vi: "Nước", pro: "shuǐ", ex: "我要喝水。(Wǒ yào hē shuǐ - Tôi muốn uống nước.)" },
        { zh: "书", vi: "Sách", pro: "shū", ex: "这本书很有趣。(Zhè běn shū hěn yǒuqù - Quyển sách này rất thú vị.)" },
        { zh: "饭", vi: "Cơm, bữa ăn", pro: "fàn", ex: "我们去吃饭吧。(Wǒmen qù chī fàn ba - Chúng ta đi ăn cơm nhé.)" },
        { zh: "城市", vi: "Thành phố", pro: "chéngshì", ex: "这个城市很漂亮。(Zhège chéngshì hěn piàoliang - Thành phố này rất đẹp.)" },
        { zh: "天气", vi: "Thời tiết", pro: "tiānqì", ex: "今天天气很好。(Jīntiān tiānqì hěn hǎo - Hôm nay thời tiết rất đẹp.)" },
        { zh: "问题", vi: "Vấn đề, câu hỏi", pro: "wèntí", ex: "有问题吗？(Yǒu wèntí ma - Có vấn đề gì không?)" },
        { zh: "地方", vi: "Nơi chốn, địa điểm", pro: "dìfang", ex: "这个地方很安静。(Zhège dìfang hěn ānjìng - Nơi này rất yên tĩnh.)" },
        { zh: "语言", vi: "Ngôn ngữ", pro: "yǔyán", ex: "汉语是世界上最难的语言之一。(Hànyǔ shì shìjiè shàng zuì nán de yǔyán zhī yī.)" },
        { zh: "文化", vi: "Văn hóa", pro: "wénhuà", ex: "中国文化非常丰富。(Zhōngguó wénhuà fēicháng fēngfù - Văn hóa Trung Quốc rất phong phú.)" },
        { zh: "医院", vi: "Bệnh viện", pro: "yīyuàn", ex: "医院在哪里？(Yīyuàn zài nǎlǐ - Bệnh viện ở đâu?)" },
        { zh: "公司", vi: "Công ty", pro: "gōngsī", ex: "他在大公司工作。(Tā zài dà gōngsī gōngzuò - Anh ấy làm ở công ty lớn.)" },
        { zh: "电影", vi: "Phim điện ảnh", pro: "diànyǐng", ex: "我喜欢看电影。(Wǒ xǐhuan kàn diànyǐng - Tôi thích xem phim.)" },
        { zh: "音乐", vi: "Âm nhạc", pro: "yīnyuè", ex: "音乐让我放松。(Yīnyuè ràng wǒ fàngsōng - Âm nhạc giúp tôi thư giãn.)" },
    ],
    "3. Tính từ Thường dùng (16 từ)": [
        { zh: "好", vi: "Tốt, giỏi", pro: "hǎo", ex: "你好！(Nǐ hǎo - Xin chào!)" },
        { zh: "大", vi: "To, lớn", pro: "dà", ex: "这个房间很大。(Zhège fángjiān hěn dà - Phòng này rất rộng.)" },
        { zh: "小", vi: "Nhỏ, bé", pro: "xiǎo", ex: "这只猫很小。(Zhè zhī māo hěn xiǎo - Con mèo này rất bé.)" },
        { zh: "美", vi: "Đẹp", pro: "měi", ex: "风景很美。(Fēngjǐng hěn měi - Phong cảnh rất đẹp.)" },
        { zh: "快", vi: "Nhanh", pro: "kuài", ex: "请快点！(Qǐng kuài diǎn - Nhanh lên!)" },
        { zh: "慢", vi: "Chậm", pro: "màn", ex: "慢走！(Màn zǒu - Đi chầm chậm thôi nhé!)" },
        { zh: "多", vi: "Nhiều", pro: "duō", ex: "人很多。(Rén hěn duō - Rất nhiều người.)" },
        { zh: "少", vi: "Ít", pro: "shǎo", ex: "钱不少。(Qián bù shǎo - Tiền không ít.)" },
        { zh: "热", vi: "Nóng", pro: "rè", ex: "今天很热。(Jīntiān hěn rè - Hôm nay rất nóng.)" },
        { zh: "冷", vi: "Lạnh", pro: "lěng", ex: "冬天很冷。(Dōngtiān hěn lěng - Mùa đông rất lạnh.)" },
        { zh: "忙", vi: "Bận rộn", pro: "máng", ex: "最近很忙。(Zuìjìn hěn máng - Dạo này rất bận.)" },
        { zh: "累", vi: "Mệt mỏi", pro: "lèi", ex: "我很累了。(Wǒ hěn lèi le - Tôi rất mệt rồi.)" },
        { zh: "高兴", vi: "Vui vẻ, hạnh phúc", pro: "gāoxìng", ex: "我很高兴认识你。(Wǒ hěn gāoxìng rènshi nǐ - Tôi rất vui được gặp bạn.)" },
        { zh: "难", vi: "Khó", pro: "nán", ex: "中文很难吗？(Zhōngwén hěn nán ma - Tiếng Trung có khó không?)" },
        { zh: "容易", vi: "Dễ dàng", pro: "róngyì", ex: "这道题很容易。(Zhè dào tí hěn róngyì - Bài toán này rất dễ.)" },
        { zh: "有趣", vi: "Thú vị", pro: "yǒuqù", ex: "这本书很有趣。(Zhè běn shū hěn yǒuqù - Quyển sách này rất thú vị.)" },
    ],
    "4. Số đếm & Thời gian (16 từ)": [
        { zh: "一", vi: "Một", pro: "yī", ex: "一个苹果。(Yī gè píngguǒ - Một quả táo.)" },
        { zh: "二 / 两", vi: "Hai", pro: "èr / liǎng", ex: "两个人。(Liǎng gè rén - Hai người.)" },
        { zh: "三", vi: "Ba", pro: "sān", ex: "三点钟。(Sān diǎn zhōng - Ba giờ đồng hồ.)" },
        { zh: "十", vi: "Mười", pro: "shí", ex: "十块钱。(Shí kuài qián - Mười đồng.)" },
        { zh: "百", vi: "Trăm", pro: "bǎi", ex: "一百个人。(Yī bǎi gè rén - Một trăm người.)" },
        { zh: "今天", vi: "Hôm nay", pro: "jīntiān", ex: "今天是星期几？(Jīntiān shì xīngqī jǐ - Hôm nay là thứ mấy?)" },
        { zh: "明天", vi: "Ngày mai", pro: "míngtiān", ex: "明天见！(Míngtiān jiàn - Hẹn gặp lại ngày mai!)" },
        { zh: "昨天", vi: "Hôm qua", pro: "zuótiān", ex: "昨天我去了超市。(Zuótiān wǒ qùle chāoshì - Hôm qua tôi đi siêu thị.)" },
        { zh: "上午", vi: "Buổi sáng (trước trưa)", pro: "shàngwǔ", ex: "上午九点见面。(Shàngwǔ jiǔ diǎn jiànmiàn - Gặp nhau lúc 9 giờ sáng.)" },
        { zh: "下午", vi: "Buổi chiều", pro: "xiàwǔ", ex: "下午三点开始。(Xiàwǔ sān diǎn kāishǐ - Bắt đầu lúc 3 giờ chiều.)" },
        { zh: "晚上", vi: "Buổi tối", pro: "wǎnshang", ex: "晚上好！(Wǎnshang hǎo - Chào buổi tối!)" },
        { zh: "年", vi: "Năm", pro: "nián", ex: "今年是龙年。(Jīnnián shì lóngnián - Năm nay là năm Rồng.)" },
        { zh: "月", vi: "Tháng", pro: "yuè", ex: "这个月很忙。(Zhège yuè hěn máng - Tháng này rất bận.)" },
        { zh: "星期", vi: "Tuần lễ", pro: "xīngqī", ex: "下个星期见。(Xià gè xīngqī jiàn - Tuần sau gặp nhau.)" },
        { zh: "现在", vi: "Bây giờ, hiện tại", pro: "xiànzài", ex: "现在几点了？(Xiànzài jǐ diǎn le - Bây giờ mấy giờ rồi?)" },
        { zh: "以后", vi: "Sau này, tương lai", pro: "yǐhòu", ex: "以后再说。(Yǐhòu zài shuō - Sau hãy nói.)" },
    ],
    "5. Giao tiếp Hàng ngày (16 từ)": [
        { zh: "谢谢", vi: "Cảm ơn", pro: "xièxie", ex: "谢谢你的帮助！(Xièxie nǐ de bāngzhù - Cảm ơn sự giúp đỡ của bạn!)" },
        { zh: "对不起", vi: "Xin lỗi", pro: "duìbuqǐ", ex: "对不起，我迟到了。(Duìbuqǐ, wǒ chídào le - Xin lỗi, tôi đến trễ.)" },
        { zh: "没关系", vi: "Không sao", pro: "méi guānxi", ex: "没关系，没问题。(Méi guānxi, méi wèntí - Không sao, không có vấn đề gì.)" },
        { zh: "请", vi: "Xin, mời", pro: "qǐng", ex: "请坐。(Qǐng zuò - Mời ngồi.)" },
        { zh: "再见", vi: "Tạm biệt", pro: "zàijiàn", ex: "明天见，再见！(Míngtiān jiàn, zàijiàn - Hẹn gặp lại ngày mai, tạm biệt!)" },
        { zh: "好的", vi: "Được rồi, ok", pro: "hǎo de", ex: "好的，我明白了。(Hǎo de, wǒ míngbái le - Được rồi, tôi hiểu.)" },
        { zh: "不", vi: "Không (phủ định)", pro: "bù", ex: "我不去。(Wǒ bú qù - Tôi không đi.)" },
        { zh: "是的", vi: "Đúng vậy, phải", pro: "shì de", ex: "是的，你说得对。(Shì de, nǐ shuō de duì - Đúng, bạn nói đúng.)" },
        { zh: "知道了", vi: "Biết rồi, hiểu rồi", pro: "zhīdào le", ex: "知道了，谢谢提醒。(Zhīdào le, xièxie tíxǐng - Biết rồi, cảm ơn đã nhắc nhở.)" },
        { zh: "多少钱", vi: "Bao nhiêu tiền?", pro: "duōshao qián", ex: "这个多少钱？(Zhège duōshao qián - Cái này bao nhiêu tiền?)" },
        { zh: "在哪里", vi: "Ở đâu?", pro: "zài nǎlǐ", ex: "洗手间在哪里？(Xǐshǒujiān zài nǎlǐ - Nhà vệ sinh ở đâu?)" },
        { zh: "怎么", vi: "Như thế nào, tại sao", pro: "zěnme", ex: "这个怎么说？(Zhège zěnme shuō - Cái này nói thế nào?)" },
        { zh: "为什么", vi: "Tại sao?", pro: "wèishénme", ex: "你为什么这样做？(Nǐ wèishénme zhèyàng zuò - Tại sao bạn làm thế?)" },
        { zh: "什么时候", vi: "Khi nào?", pro: "shénme shíhou", ex: "你什么时候来？(Nǐ shénme shíhou lái - Bạn đến khi nào?)" },
        { zh: "可以", vi: "Có thể, được phép", pro: "kěyǐ", ex: "我可以坐这里吗？(Wǒ kěyǐ zuò zhèlǐ ma - Tôi có thể ngồi đây không?)" },
        { zh: "一起", vi: "Cùng nhau", pro: "yīqǐ", ex: "我们一起去吧！(Wǒmen yīqǐ qù ba - Chúng ta cùng đi thôi!)" },
    ],
};
