const defaultData = {
    "1. Động từ Cốt lõi (20 từ)": [
        { en: "Be", vi: "Thì, là, ở", pro: "/biː/", ex: "I want to be a SOC Analyst." },
        { en: "Have", vi: "Có", pro: "/hæv/", ex: "I have a lot of work to do." },
        { en: "Do", vi: "Làm", pro: "/duː/", ex: "Just do it!" },
        { en: "Say", vi: "Nói", pro: "/seɪ/", ex: "What did you say?" },
        { en: "Get", vi: "Lấy, nhận được", pro: "/ɡet/", ex: "I need to get some sleep." },
        { en: "Make", vi: "Làm, chế tạo", pro: "/meɪk/", ex: "She makes me happy." },
        { en: "Go", vi: "Đi", pro: "/ɡoʊ/", ex: "Let's go home." },
        { en: "Know", vi: "Biết", pro: "/noʊ/", ex: "I don't know the answer." },
        { en: "Take", vi: "Cầm, nắm, lấy", pro: "/teɪk/", ex: "Take my hand." },
        { en: "See", vi: "Nhìn thấy", pro: "/siː/", ex: "I see a bird." },
        { en: "Come", vi: "Đến", pro: "/kʌm/", ex: "Come here, please." },
        { en: "Think", vi: "Nghĩ", pro: "/θɪŋk/", ex: "I think it is raining." },
        { en: "Look", vi: "Nhìn", pro: "/lʊk/", ex: "Look at that car!" },
        { en: "Want", vi: "Muốn", pro: "/wɒnt/", ex: "I want a cup of coffee." },
        { en: "Give", vi: "Cho, đưa", pro: "/ɡɪv/", ex: "Give me the book." },
        { en: "Use", vi: "Sử dụng", pro: "/juːz/", ex: "Can I use your phone?" },
        { en: "Find", vi: "Tìm thấy", pro: "/faɪnd/", ex: "I can't find my keys." },
        { en: "Tell", vi: "Nói, bảo", pro: "/tel/", ex: "Tell me the truth." },
        { en: "Ask", vi: "Hỏi", pro: "/ɑːsk/", ex: "Can I ask a question?" },
        { en: "Work", vi: "Làm việc", pro: "/wɜːk/", ex: "I work every day." }
    ],
    "2. Danh từ Quen thuộc (20 từ)": [
        { en: "Time", vi: "Thời gian", pro: "/taɪm/", ex: "What time is it?" },
        { en: "Person", vi: "Con người", pro: "/ˈpɜː.sən/", ex: "She is a nice person." },
        { en: "Year", vi: "Năm", pro: "/jɪər/", ex: "Happy New Year!" },
        { en: "Way", vi: "Đường, cách thức", pro: "/weɪ/", ex: "Show me the way." },
        { en: "Day", vi: "Ngày", pro: "/deɪ/", ex: "Have a good day." },
        { en: "Thing", vi: "Thứ, đồ vật", pro: "/θɪŋ/", ex: "What is this thing?" },
        { en: "Man", vi: "Đàn ông", pro: "/mæn/", ex: "He is a strong man." },
        { en: "World", vi: "Thế giới", pro: "/wɜːld/", ex: "The world is big." },
        { en: "Life", vi: "Cuộc sống", pro: "/laɪf/", ex: "Life is beautiful." },
        { en: "Hand", vi: "Bàn tay", pro: "/hænd/", ex: "Wash your hands." },
        { en: "Part", vi: "Phần, bộ phận", pro: "/pɑːt/", ex: "This is the best part." },
        { en: "Child", vi: "Trẻ em", pro: "/tʃaɪld/", ex: "The child is playing." },
        { en: "Eye", vi: "Mắt", pro: "/aɪ/", ex: "Close your eyes." },
        { en: "Woman", vi: "Phụ nữ", pro: "/ˈwʊm.ən/", ex: "She is a smart woman." },
        { en: "Place", vi: "Nơi chốn", pro: "/pleɪs/", ex: "This is a good place." },
        { en: "Work", vi: "Công việc", pro: "/wɜːk/", ex: "I have a lot of work." },
        { en: "Week", vi: "Tuần", pro: "/wiːk/", ex: "See you next week." },
        { en: "Case", vi: "Trường hợp", pro: "/keɪs/", ex: "In that case, I will go." },
        { en: "Point", vi: "Điểm, ý chính", pro: "/pɔɪnt/", ex: "That is a good point." },
        { en: "Company", vi: "Công ty", pro: "/ˈkʌm.pə.ni/", ex: "I work for a tech company." }
    ],
    "3. Tính từ Miêu tả (20 từ)": [
        { en: "Good", vi: "Tốt", pro: "/ɡʊd/", ex: "This is a good book." },
        { en: "New", vi: "Mới", pro: "/njuː/", ex: "I have a new phone." },
        { en: "First", vi: "Đầu tiên", pro: "/fɜːst/", ex: "He is the first one here." },
        { en: "Last", vi: "Cuối cùng", pro: "/lɑːst/", ex: "This is my last chance." },
        { en: "Long", vi: "Dài", pro: "/lɒŋ/", ex: "It is a long road." },
        { en: "Great", vi: "Tuyệt vời", pro: "/ɡreɪt/", ex: "You did a great job." },
        { en: "Little", vi: "Nhỏ, ít", pro: "/ˈlɪt.əl/", ex: "I need a little help." },
        { en: "Own", vi: "Riêng, sở hữu", pro: "/oʊn/", ex: "I have my own room." },
        { en: "Other", vi: "Khác", pro: "/ˈʌð.ər/", ex: "Do you have any other questions?" },
        { en: "Old", vi: "Cũ, già", pro: "/oʊld/", ex: "This car is very old." },
        { en: "Right", vi: "Đúng, phải", pro: "/raɪt/", ex: "You are absolutely right." },
        { en: "Big", vi: "Lớn", pro: "/bɪɡ/", ex: "That is a big house." },
        { en: "High", vi: "Cao", pro: "/haɪ/", ex: "The mountain is very high." },
        { en: "Different", vi: "Khác biệt", pro: "/ˈdɪf.ər.ənt/", ex: "We have different ideas." },
        { en: "Small", vi: "Nhỏ", pro: "/smɔːl/", ex: "It is a small problem." },
        { en: "Large", vi: "Rộng lớn", pro: "/lɑːdʒ/", ex: "They live in a large city." },
        { en: "Next", vi: "Tiếp theo", pro: "/nekst/", ex: "Who is the next person?" },
        { en: "Early", vi: "Sớm", pro: "/ˈɜː.li/", ex: "I woke up early today." },
        { en: "Young", vi: "Trẻ", pro: "/jʌŋ/", ex: "He is a young boy." },
        { en: "Important", vi: "Quan trọng", pro: "/ɪmˈpɔː.tənt/", ex: "This meeting is important." }
    ],
    "4. Trạng từ & Nơi chốn (20 từ)": [
        { en: "Up", vi: "Lên", pro: "/ʌp/", ex: "Look up at the sky." },
        { en: "So", vi: "Vì vậy, quá", pro: "/soʊ/", ex: "I am so happy." },
        { en: "Out", vi: "Ra ngoài", pro: "/aʊt/", ex: "Let's go out." },
        { en: "Just", vi: "Chỉ, vừa mới", pro: "/dʒʌst/", ex: "I just arrived." },
        { en: "Now", vi: "Bây giờ", pro: "/naʊ/", ex: "Do it right now." },
        { en: "How", vi: "Như thế nào", pro: "/haʊ/", ex: "How are you?" },
        { en: "Then", vi: "Sau đó", pro: "/ðen/", ex: "We ate, and then we left." },
        { en: "More", vi: "Nhiều hơn", pro: "/mɔːr/", ex: "I need more time." },
        { en: "Also", vi: "Cũng", pro: "/ˈɔːl.soʊ/", ex: "She is also a student." },
        { en: "Here", vi: "Ở đây", pro: "/hɪər/", ex: "Come over here." },
        { en: "Well", vi: "Tốt", pro: "/wel/", ex: "He plays football well." },
        { en: "Only", vi: "Chỉ", pro: "/ˈoʊn.li/", ex: "I have only one sister." },
        { en: "Very", vi: "Rất", pro: "/ˈver.i/", ex: "Thank you very much." },
        { en: "Even", vi: "Thậm chí", pro: "/ˈiː.vən/", ex: "Even a child knows that." },
        { en: "Back", vi: "Trở lại", pro: "/bæk/", ex: "I will be back soon." },
        { en: "There", vi: "Ở đó", pro: "/ðeər/", ex: "Look over there." },
        { en: "Down", vi: "Xuống", pro: "/daʊn/", ex: "Sit down, please." },
        { en: "Still", vi: "Vẫn", pro: "/stɪl/", ex: "I am still waiting." },
        { en: "In", vi: "Trong", pro: "/ɪn/", ex: "She is in the room." },
        { en: "As", vi: "Như", pro: "/æz/", ex: "Do as I say." }
    ],
    "5. Nối câu & Đại từ (20 từ)": [
        { en: "And", vi: "Và", pro: "/ænd/", ex: "You and me." },
        { en: "But", vi: "Nhưng", pro: "/bʌt/", ex: "I tried, but I failed." },
        { en: "Or", vi: "Hoặc", pro: "/ɔːr/", ex: "Tea or coffee?" },
        { en: "Because", vi: "Bởi vì", pro: "/bɪˈkɒz/", ex: "I smile because I am happy." },
        { en: "If", vi: "Nếu", pro: "/ɪf/", ex: "If it rains, I will stay." },
        { en: "When", vi: "Khi nào", pro: "/wen/", ex: "When will you come?" },
        { en: "Than", vi: "Hơn", pro: "/ðæn/", ex: "He is taller than me." },
        { en: "That", vi: "Rằng, kia", pro: "/ðæt/", ex: "I know that you are right." },
        { en: "This", vi: "Này", pro: "/ðɪs/", ex: "This is my house." },
        { en: "They", vi: "Họ", pro: "/ðeɪ/", ex: "They are my friends." },
        { en: "We", vi: "Chúng ta", pro: "/wiː/", ex: "We can do it." },
        { en: "She", vi: "Cô ấy", pro: "/ʃiː/", ex: "She is very smart." },
        { en: "Who", vi: "Ai", pro: "/huː/", ex: "Who is that?" },
        { en: "What", vi: "Cái gì", pro: "/wɒt/", ex: "What is your name?" },
        { en: "Where", vi: "Ở đâu", pro: "/weər/", ex: "Where do you live?" },
        { en: "Why", vi: "Tại sao", pro: "/waɪ/", ex: "Why are you crying?" },
        { en: "Which", vi: "Cái nào", pro: "/wɪtʃ/", ex: "Which one do you like?" },
        { en: "Some", vi: "Một vài", pro: "/sʌm/", ex: "I need some water." },
        { en: "Any", vi: "Bất kỳ", pro: "/ˈen.i/", ex: "Do you have any questions?" },
        { en: "All", vi: "Tất cả", pro: "/ɔːl/", ex: "All of us are ready." }
    ]
};