/* Generated by build.py. Edit data.js and src/*.js instead. */

// ---- src/00-start.js ----
(() => {
    "use strict";

    const BRAND_NAME = "ZeroEnglish";
    const STORAGE_KEYS = {
        customTopics: "zeroenglish.custom.topics",
        savedWords: "zeroenglish.saved.words",
    };

// ---- data.js ----
const defaultData = {
    "1. Động từ Cốt lõi (20 từ)": [
        { en: "Be", vi: "Thì, là, ở", pro: "/biː/", ex: "I want to be a SOC Analyst." },
        { en: "Have", vi: "Có", pro: "/hæv/", ex: "I have a lot of work to do." },
        { en: "Do", vi: "Làm", pro: "/duː/", ex: "Just do it!" },
        { en: "Say", vi: "Nói", pro: "/seɪ/", ex: "What did you say?" },
        { en: "Get", vi: "Lấy, nhận được", pro: "/ɡet/", ex: "I need to get some sleep." },
        { en: "Make", vi: "Làm, chế tạo", pro: "/meɪk/", ex: "She makes me happy." },
        { en: "Go", vi: "Đi", pro: "/ɡoʊ/", ex: "Let's go home." },
        { en: "Know", vi: "Biết", pro: "/noʊ/", ex: "I don't know the answer." },
        { en: "Take", vi: "Cầm, nắm, lấy", pro: "/teɪk/", ex: "Take my hand." },
        { en: "See", vi: "Nhìn thấy", pro: "/siː/", ex: "I see a bird." },
        { en: "Come", vi: "Đến", pro: "/kʌm/", ex: "Come here, please." },
        { en: "Think", vi: "Nghĩ", pro: "/θɪŋk/", ex: "I think it is raining." },
        { en: "Look", vi: "Nhìn", pro: "/lʊk/", ex: "Look at that car!" },
        { en: "Want", vi: "Muốn", pro: "/wɒnt/", ex: "I want a cup of coffee." },
        { en: "Give", vi: "Cho, đưa", pro: "/ɡɪv/", ex: "Give me the book." },
        { en: "Use", vi: "Sử dụng", pro: "/juːz/", ex: "Can I use your phone?" },
        { en: "Find", vi: "Tìm thấy", pro: "/faɪnd/", ex: "I can't find my keys." },
        { en: "Tell", vi: "Nói, bảo", pro: "/tel/", ex: "Tell me the truth." },
        { en: "Ask", vi: "Hỏi", pro: "/ɑːsk/", ex: "Can I ask a question?" },
        { en: "Work", vi: "Làm việc", pro: "/wɜːk/", ex: "I work every day." }
    ],
    "2. Danh từ Quen thuộc (20 từ)": [
        { en: "Time", vi: "Thời gian", pro: "/taɪm/", ex: "What time is it?" },
        { en: "Person", vi: "Con người", pro: "/ˈpɜː.sən/", ex: "She is a nice person." },
        { en: "Year", vi: "Năm", pro: "/jɪər/", ex: "Happy New Year!" },
        { en: "Way", vi: "Đường, cách thức", pro: "/weɪ/", ex: "Show me the way." },
        { en: "Day", vi: "Ngày", pro: "/deɪ/", ex: "Have a good day." },
        { en: "Thing", vi: "Thứ, đồ vật", pro: "/θɪŋ/", ex: "What is this thing?" },
        { en: "Man", vi: "Đàn ông", pro: "/mæn/", ex: "He is a strong man." },
        { en: "World", vi: "Thế giới", pro: "/wɜːld/", ex: "The world is big." },
        { en: "Life", vi: "Cuộc sống", pro: "/laɪf/", ex: "Life is beautiful." },
        { en: "Hand", vi: "Bàn tay", pro: "/hænd/", ex: "Wash your hands." },
        { en: "Part", vi: "Phần, bộ phận", pro: "/pɑːt/", ex: "This is the best part." },
        { en: "Child", vi: "Trẻ em", pro: "/tʃaɪld/", ex: "The child is playing." },
        { en: "Eye", vi: "Mắt", pro: "/aɪ/", ex: "Close your eyes." },
        { en: "Woman", vi: "Phụ nữ", pro: "/ˈwʊm.ən/", ex: "She is a smart woman." },
        { en: "Place", vi: "Nơi chốn", pro: "/pleɪs/", ex: "This is a good place." },
        { en: "Work", vi: "Công việc", pro: "/wɜːk/", ex: "I have a lot of work." },
        { en: "Week", vi: "Tuần", pro: "/wiːk/", ex: "See you next week." },
        { en: "Case", vi: "Trường hợp", pro: "/keɪs/", ex: "In that case, I will go." },
        { en: "Point", vi: "Điểm, ý chính", pro: "/pɔɪnt/", ex: "That is a good point." },
        { en: "Company", vi: "Công ty", pro: "/ˈkʌm.pə.ni/", ex: "I work for a tech company." }
    ],
    "3. Tính từ Miêu tả (20 từ)": [
        { en: "Good", vi: "Tốt", pro: "/ɡʊd/", ex: "This is a good book." },
        { en: "New", vi: "Mới", pro: "/njuː/", ex: "I have a new phone." },
        { en: "First", vi: "Đầu tiên", pro: "/fɜːst/", ex: "He is the first one here." },
        { en: "Last", vi: "Cuối cùng", pro: "/lɑːst/", ex: "This is my last chance." },
        { en: "Long", vi: "Dài", pro: "/lɒŋ/", ex: "It is a long road." },
        { en: "Great", vi: "Tuyệt vời", pro: "/ɡreɪt/", ex: "You did a great job." },
        { en: "Little", vi: "Nhỏ, ít", pro: "/ˈlɪt.əl/", ex: "I need a little help." },
        { en: "Own", vi: "Riêng, sở hữu", pro: "/oʊn/", ex: "I have my own room." },
        { en: "Other", vi: "Khác", pro: "/ˈʌð.ər/", ex: "Do you have any other questions?" },
        { en: "Old", vi: "Cũ, già", pro: "/oʊld/", ex: "This car is very old." },
        { en: "Right", vi: "Đúng, phải", pro: "/raɪt/", ex: "You are absolutely right." },
        { en: "Big", vi: "Lớn", pro: "/bɪɡ/", ex: "That is a big house." },
        { en: "High", vi: "Cao", pro: "/haɪ/", ex: "The mountain is very high." },
        { en: "Different", vi: "Khác biệt", pro: "/ˈdɪf.ər.ənt/", ex: "We have different ideas." },
        { en: "Small", vi: "Nhỏ", pro: "/smɔːl/", ex: "It is a small problem." },
        { en: "Large", vi: "Rộng lớn", pro: "/lɑːdʒ/", ex: "They live in a large city." },
        { en: "Next", vi: "Tiếp theo", pro: "/nekst/", ex: "Who is the next person?" },
        { en: "Early", vi: "Sớm", pro: "/ˈɜː.li/", ex: "I woke up early today." },
        { en: "Young", vi: "Trẻ", pro: "/jʌŋ/", ex: "He is a young boy." },
        { en: "Important", vi: "Quan trọng", pro: "/ɪmˈpɔː.tənt/", ex: "This meeting is important." }
    ],
    "4. Trạng từ & Nơi chốn (20 từ)": [
        { en: "Up", vi: "Lên", pro: "/ʌp/", ex: "Look up at the sky." },
        { en: "So", vi: "Vì vậy, quá", pro: "/soʊ/", ex: "I am so happy." },
        { en: "Out", vi: "Ra ngoài", pro: "/aʊt/", ex: "Let's go out." },
        { en: "Just", vi: "Chỉ, vừa mới", pro: "/dʒʌst/", ex: "I just arrived." },
        { en: "Now", vi: "Bây giờ", pro: "/naʊ/", ex: "Do it right now." },
        { en: "How", vi: "Như thế nào", pro: "/haʊ/", ex: "How are you?" },
        { en: "Then", vi: "Sau đó", pro: "/ðen/", ex: "We ate, and then we left." },
        { en: "More", vi: "Nhiều hơn", pro: "/mɔːr/", ex: "I need more time." },
        { en: "Also", vi: "Cũng", pro: "/ˈɔːl.soʊ/", ex: "She is also a student." },
        { en: "Here", vi: "Ở đây", pro: "/hɪər/", ex: "Come over here." },
        { en: "Well", vi: "Tốt", pro: "/wel/", ex: "He plays football well." },
        { en: "Only", vi: "Chỉ", pro: "/ˈoʊn.li/", ex: "I have only one sister." },
        { en: "Very", vi: "Rất", pro: "/ˈver.i/", ex: "Thank you very much." },
        { en: "Even", vi: "Thậm chí", pro: "/ˈiː.vən/", ex: "Even a child knows that." },
        { en: "Back", vi: "Trở lại", pro: "/bæk/", ex: "I will be back soon." },
        { en: "There", vi: "Ở đó", pro: "/ðeər/", ex: "Look over there." },
        { en: "Down", vi: "Xuống", pro: "/daʊn/", ex: "Sit down, please." },
        { en: "Still", vi: "Vẫn", pro: "/stɪl/", ex: "I am still waiting." },
        { en: "In", vi: "Trong", pro: "/ɪn/", ex: "She is in the room." },
        { en: "As", vi: "Như", pro: "/æz/", ex: "Do as I say." }
    ],
    "5. Nối câu & Đại từ (20 từ)": [
        { en: "And", vi: "Và", pro: "/ænd/", ex: "You and me." },
        { en: "But", vi: "Nhưng", pro: "/bʌt/", ex: "I tried, but I failed." },
        { en: "Or", vi: "Hoặc", pro: "/ɔːr/", ex: "Tea or coffee?" },
        { en: "Because", vi: "Bởi vì", pro: "/bɪˈkɒz/", ex: "I smile because I am happy." },
        { en: "If", vi: "Nếu", pro: "/ɪf/", ex: "If it rains, I will stay." },
        { en: "When", vi: "Khi nào", pro: "/wen/", ex: "When will you come?" },
        { en: "Than", vi: "Hơn", pro: "/ðæn/", ex: "He is taller than me." },
        { en: "That", vi: "Rằng, kia", pro: "/ðæt/", ex: "I know that you are right." },
        { en: "This", vi: "Này", pro: "/ðɪs/", ex: "This is my house." },
        { en: "They", vi: "Họ", pro: "/ðeɪ/", ex: "They are my friends." },
        { en: "We", vi: "Chúng ta", pro: "/wiː/", ex: "We can do it." },
        { en: "She", vi: "Cô ấy", pro: "/ʃiː/", ex: "She is very smart." },
        { en: "Who", vi: "Ai", pro: "/huː/", ex: "Who is that?" },
        { en: "What", vi: "Cái gì", pro: "/wɒt/", ex: "What is your name?" },
        { en: "Where", vi: "Ở đâu", pro: "/weər/", ex: "Where do you live?" },
        { en: "Why", vi: "Tại sao", pro: "/waɪ/", ex: "Why are you crying?" },
        { en: "Which", vi: "Cái nào", pro: "/wɪtʃ/", ex: "Which one do you like?" },
        { en: "Some", vi: "Một vài", pro: "/sʌm/", ex: "I need some water." },
        { en: "Any", vi: "Bất kỳ", pro: "/ˈen.i/", ex: "Do you have any questions?" },
        { en: "All", vi: "Tất cả", pro: "/ɔːl/", ex: "All of us are ready." }
    ]
};

// ---- src/10-utils.js ----
    function safeParse(rawValue, fallback) {
        if (!rawValue) {
            return fallback;
        }

        try {
            const parsed = JSON.parse(rawValue);
            return parsed ?? fallback;
        } catch {
            return fallback;
        }
    }

    function cloneData(value) {
        return JSON.parse(JSON.stringify(value));
    }

    function clearNode(node) {
        while (node.firstChild) {
            node.removeChild(node.firstChild);
        }
    }

    function createElement(tagName, className, text) {
        const element = document.createElement(tagName);
        if (className) {
            element.className = className;
        }
        if (typeof text === "string") {
            element.textContent = text;
        }
        return element;
    }

    function show(element) {
        element.classList.remove("hidden");
    }

    function hide(element) {
        element.classList.add("hidden");
    }

    function shuffle(items) {
        const next = [...items];
        for (let index = next.length - 1; index > 0; index -= 1) {
            const swapIndex = Math.floor(Math.random() * (index + 1));
            [next[index], next[swapIndex]] = [next[swapIndex], next[index]];
        }
        return next;
    }

    function normalizeLookupKey(value) {
        return String(value || "")
            .toLowerCase()
            .replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
    }

    function showError(message) {
        window.alert(message);
    }

    function setBusy(button, isBusy, busyText) {
        if (!button) {
            return;
        }

        if (!button.dataset.defaultLabel) {
            button.dataset.defaultLabel = button.textContent || "";
        }

        button.disabled = isBusy;
        button.textContent = isBusy ? busyText : button.dataset.defaultLabel;
    }

// ---- src/20-api.js ----
    async function parseResponse(response) {
        const rawText = await response.text();
        let data = {};

        if (rawText) {
            try {
                data = JSON.parse(rawText);
            } catch {
                throw new Error("Server trả về dữ liệu không đọc được.");
            }
        }

        if (!response.ok) {
            throw new Error(data.error || "Yêu cầu thất bại.");
        }

        return data;
    }

    async function postJson(path, payload) {
        const response = await fetch(path, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            body: JSON.stringify(payload),
        });
        return parseResponse(response);
    }

    const api = {
        getBootstrap() {
            return fetch("/api/bootstrap", {
                headers: {
                    "Accept": "application/json",
                },
            }).then(parseResponse);
        },
        generateTopic(topic) {
            return postJson("/api/ai/topic", { topic });
        },
        explainSentence(sentence) {
            return postJson("/api/ai/explain", { sentence });
        },
        generateReading(level) {
            return postJson("/api/ai/reading", { level });
        },
        generateGrammar(topic) {
            return postJson("/api/ai/grammar", { topic });
        },
        chat(history) {
            return postJson("/api/ai/chat", { history });
        },
        generateListening(level) {
            return postJson("/api/ai/listening", { level });
        },
        generateMatching(level) {
            return postJson("/api/ai/matching", { level });
        },
    };

// ---- src/30-state.js ----
    const baseData = typeof defaultData === "object" && defaultData ? cloneData(defaultData) : {};
    const savedTopics = safeParse(localStorage.getItem(STORAGE_KEYS.customTopics), {});
    const savedWordsSeed = safeParse(localStorage.getItem(STORAGE_KEYS.savedWords), []);

    const state = {
        bootstrap: {
            brand: BRAND_NAME,
            aiEnabled: false,
            secureMode: false,
        },
        appData: Object.assign({}, baseData, savedTopics),
        savedWordsList: Array.isArray(savedWordsSeed) ? savedWordsSeed : [],
        currentTopic: null,
        currentIndex: 0,
        currentReadingVocab: {},
        chatHistory: [],
        currentListening: {
            transcript: "",
            questions: [],
            utterance: null,
        },
        matching: {
            level: "easy",
            pairs: [],
            enOrder: [],
            viOrder: [],
            matchedIds: new Set(),
            selected: {
                en: null,
                vi: null,
            },
            lastSource: "",
        },
        flashcardInteraction: {
            pointerId: null,
            startX: 0,
            startY: 0,
            startTime: 0,
            isAnimating: false,
        },
    };

    function persistCustomTopics() {
        const customTopics = {};
        Object.keys(state.appData).forEach((topicName) => {
            if (!Object.prototype.hasOwnProperty.call(baseData, topicName)) {
                customTopics[topicName] = state.appData[topicName];
            }
        });
        localStorage.setItem(STORAGE_KEYS.customTopics, JSON.stringify(customTopics));
    }

    function persistSavedWords() {
        localStorage.setItem(STORAGE_KEYS.savedWords, JSON.stringify(state.savedWordsList));
    }

    function getCurrentWord() {
        if (!state.currentTopic) {
            return null;
        }
        const words = state.appData[state.currentTopic] || [];
        return words[state.currentIndex] || null;
    }

    function isSavedWord(word) {
        const targetKey = normalizeLookupKey(word?.en);
        return state.savedWordsList.some((item) => normalizeLookupKey(item.en) === targetKey);
    }

    function toggleSavedWord(word) {
        const targetKey = normalizeLookupKey(word?.en);
        const existingIndex = state.savedWordsList.findIndex((item) => normalizeLookupKey(item.en) === targetKey);

        if (existingIndex >= 0) {
            state.savedWordsList.splice(existingIndex, 1);
            persistSavedWords();
            return false;
        }

        state.savedWordsList.push(cloneData(word));
        persistSavedWords();
        return true;
    }

// ---- src/40-dom.js ----
    const refs = {
        appStatusBanner: document.getElementById("appStatusBanner"),
        strictAiButtons: Array.from(document.querySelectorAll('[data-ai-required="strict"]')),
        tabButtons: Array.from(document.querySelectorAll(".tab-btn")),
        views: Array.from(document.querySelectorAll(".view-section")),
        topicInput: document.getElementById("topicInput"),
        generateBtn: document.getElementById("generateBtn"),
        loadingMsg: document.getElementById("loadingMsg"),
        topicList: document.getElementById("topicList"),
        currentTopicTitle: document.getElementById("currentTopicTitle"),
        progressText: document.getElementById("progressText"),
        cardContainer: document.getElementById("cardContainer"),
        flashcard: document.getElementById("flashcard"),
        wordEn: document.getElementById("wordEn"),
        wordPro: document.getElementById("wordPro"),
        wordVi: document.getElementById("wordVi"),
        wordEx: document.getElementById("wordEx"),
        actionButtons: document.getElementById("actionButtons"),
        saveWordBtn: document.getElementById("saveWordBtn"),
        explainGrammarBtn: document.getElementById("explainGrammarBtn"),
        explanationBox: document.getElementById("explanationBox"),
        explanationText: document.getElementById("explanationText"),
        controls: document.getElementById("controls"),
        prevBtn: document.getElementById("prevBtn"),
        nextBtn: document.getElementById("nextBtn"),
        levelSelect: document.getElementById("levelSelect"),
        generateReadingBtn: document.getElementById("generateReadingBtn"),
        readingLoadingMsg: document.getElementById("readingLoadingMsg"),
        readingBox: document.getElementById("readingBox"),
        readingTitle: document.getElementById("readingTitle"),
        readingContent: document.getElementById("readingContent"),
        toggleTranslationBtn: document.getElementById("toggleTranslationBtn"),
        fullTranslationBox: document.getElementById("fullTranslationBox"),
        tooltip: document.getElementById("tooltip"),
        grammarSelect: document.getElementById("grammarSelect"),
        generateGrammarBtn: document.getElementById("generateGrammarBtn"),
        grammarLoadingMsg: document.getElementById("grammarLoadingMsg"),
        grammarBox: document.getElementById("grammarBox"),
        grammarTitle: document.getElementById("grammarTitle"),
        grammarFormula: document.getElementById("grammarFormula"),
        grammarUsage: document.getElementById("grammarUsage"),
        grammarExamples: document.getElementById("grammarExamples"),
        chatBox: document.getElementById("chatBox"),
        chatInput: document.getElementById("chatInput"),
        sendChatBtn: document.getElementById("sendChatBtn"),
        listenLevelSelect: document.getElementById("listenLevelSelect"),
        generateListenBtn: document.getElementById("generateListenBtn"),
        listenLoadingMsg: document.getElementById("listenLoadingMsg"),
        listeningBox: document.getElementById("listeningBox"),
        playAudioBtn: document.getElementById("playAudioBtn"),
        pauseAudioBtn: document.getElementById("pauseAudioBtn"),
        stopAudioBtn: document.getElementById("stopAudioBtn"),
        quizContainer: document.getElementById("quizContainer"),
        submitQuizBtn: document.getElementById("submitQuizBtn"),
        showTranscriptBtn: document.getElementById("showTranscriptBtn"),
        quizResult: document.getElementById("quizResult"),
        transcriptBox: document.getElementById("transcriptBox"),
        matchingLevelSelect: document.getElementById("matchingLevelSelect"),
        generateMatchingBtn: document.getElementById("generateMatchingBtn"),
        matchingLoadingMsg: document.getElementById("matchingLoadingMsg"),
        matchingBox: document.getElementById("matchingBox"),
        matchingProgressText: document.getElementById("matchingProgressText"),
        resetMatchingBtn: document.getElementById("resetMatchingBtn"),
        matchingEnList: document.getElementById("matchingEnList"),
        matchingViList: document.getElementById("matchingViList"),
        matchingFeedback: document.getElementById("matchingFeedback"),
        clearSavedBtn: document.getElementById("clearSavedBtn"),
        savedWordsGrid: document.getElementById("savedWordsGrid"),
    };

// ---- src/50-tabs.js ----
    function activateTab(targetId) {
        refs.tabButtons.forEach((button) => {
            button.classList.toggle("active", button.dataset.target === targetId);
        });

        refs.views.forEach((view) => {
            view.classList.toggle("hidden", view.id !== targetId);
        });

        if (targetId === "view-saved") {
            renderSavedWords();
        }
    }

    function initTabs() {
        refs.tabButtons.forEach((button) => {
            button.addEventListener("click", () => activateTab(button.dataset.target));
        });
    }

// ---- src/60-flashcards.js ----
function setFlashcardVisibility(hasWord) {
        [refs.cardContainer, refs.actionButtons, refs.controls].forEach((element) => {
            if (hasWord) {
                show(element);
            } else {
                hide(element);
            }
        });
    }

    function updateSaveButton() {
        const currentWord = getCurrentWord();
        if (!currentWord) {
            refs.saveWordBtn.textContent = "Lưu thuật ngữ";
            return;
        }

        // Đổi chữ sang phong cách học thuật
        refs.saveWordBtn.textContent = isSavedWord(currentWord) ? "Hủy lưu thuật ngữ" : "Lưu thuật ngữ";
    }

    function resetFlashcardFlip() {
        refs.flashcard.classList.remove("is-flipped");
        refs.flashcard.classList.remove("is-animating");
        state.flashcardInteraction.isAnimating = false;
    }

    function toggleFlashcard() {
        if (!getCurrentWord() || state.flashcardInteraction.isAnimating) {
            return;
        }

        state.flashcardInteraction.isAnimating = true;
        refs.flashcard.classList.add("is-animating");
        refs.flashcard.classList.toggle("is-flipped");

        window.setTimeout(() => {
            refs.flashcard.classList.remove("is-animating");
            state.flashcardInteraction.isAnimating = false;
        }, 420);
    }

    function showCard() {
        const currentWord = getCurrentWord();
        if (!currentWord) {
            refs.currentTopicTitle.textContent = "Vui lòng chọn một chủ đề học thuật";
            refs.progressText.textContent = "0 / 0";
            setFlashcardVisibility(false);
            return;
        }

        const wordList = state.appData[state.currentTopic] || [];
        refs.currentTopicTitle.textContent = state.currentTopic;
        refs.progressText.textContent = `${state.currentIndex + 1} / ${wordList.length}`;
        refs.wordEn.textContent = currentWord.en;
        refs.wordPro.textContent = currentWord.pro || "/.../";
        refs.wordVi.textContent = currentWord.vi;
        refs.wordEx.textContent = currentWord.ex;
        updateSaveButton();
        setFlashcardVisibility(true);
    }

    function renderTopics() {
        clearNode(refs.topicList);
        const topics = Object.keys(state.appData);

        if (!topics.length) {
            refs.topicList.appendChild(createElement("li", "", "Hệ thống chưa có dữ liệu chủ đề."));
            return;
        }

        topics.forEach((topicName) => {
            const listItem = createElement("li");
            const button = createElement("button", "topic-item", topicName);
            button.type = "button";
            if (topicName === state.currentTopic) {
                button.classList.add("active");
            }
            button.addEventListener("click", () => loadTopic(topicName));
            listItem.appendChild(button);
            refs.topicList.appendChild(listItem);
        });
    }

    function loadTopic(topicName) {
        if (!state.appData[topicName]) {
            return;
        }

        state.currentTopic = topicName;
        state.currentIndex = 0;
        resetFlashcardFlip();
        hide(refs.explanationBox);
        refs.explanationText.textContent = "";
        renderTopics();
        showCard();
    }

    function stepCard(delta) {
        const wordList = state.appData[state.currentTopic] || [];
        const nextIndex = state.currentIndex + delta;

        if (nextIndex < 0 || nextIndex >= wordList.length) {
            return;
        }

        state.currentIndex = nextIndex;
        resetFlashcardFlip();
        hide(refs.explanationBox);
        refs.explanationText.textContent = "";
        showCard();
    }

    async function handleTopicGeneration() {
        const topic = refs.topicInput.value.trim();
        if (!topic) {
            showError("Vui lòng nhập từ khóa chủ đề cần tạo.");
            return;
        }
        if (state.appData[topic]) {
            showError("Chủ đề này đã tồn tại trong hệ thống.");
            return;
        }

        setBusy(refs.generateBtn, true, "Đang khởi tạo dữ liệu...");
        show(refs.loadingMsg);

        try {
            const data = await api.generateTopic(topic);
            state.appData[data.topic] = Array.isArray(data.words) ? data.words : [];
            persistCustomTopics();
            refs.topicInput.value = "";
            renderTopics();
            loadTopic(data.topic);
        } catch (error) {
            showError(error.message);
        } finally {
            setBusy(refs.generateBtn, false, "Khởi tạo chủ đề AI");
            hide(refs.loadingMsg);
        }
    }

    async function handleExplainGrammar() {
        const currentWord = getCurrentWord();
        if (!currentWord) {
            return;
        }

        refs.explanationText.textContent = "Trợ lý AI đang phân tích cấu trúc ngữ pháp...";
        show(refs.explanationBox);

        try {
            const data = await api.explainSentence(currentWord.ex);
            refs.explanationText.textContent = data.explanation;
        } catch (error) {
            refs.explanationText.textContent = error.message;
        }
    }

    function renderSavedWords() {
        clearNode(refs.savedWordsGrid);

        if (!state.savedWordsList.length) {
            refs.savedWordsGrid.appendChild(createElement("p", "", "Sổ tay thuật ngữ hiện đang trống."));
            return;
        }

        state.savedWordsList.forEach((word, index) => {
            const card = createElement("article", "saved-card");
            const title = createElement("h3", "", word.en);
            const meaning = createElement("p", "", `Định nghĩa: ${word.vi}`);
            const example = createElement("p", "", `Ngữ cảnh: ${word.ex}`);
            const removeButton = createElement("button", "btn-secondary remove-btn", "Loại bỏ");
            removeButton.type = "button";
            removeButton.dataset.removeSavedIndex = String(index);

            card.appendChild(title);
            card.appendChild(meaning);
            card.appendChild(example);
            card.appendChild(removeButton);
            refs.savedWordsGrid.appendChild(card);
        });
    }

    function initFlashcards() {
        // 1. Lật thẻ chỉ bằng 1 thao tác chạm/click duy nhất
        refs.flashcard.addEventListener("click", (event) => {
            event.preventDefault();
            toggleFlashcard();
        });

        // 2. Giữ nguyên lật thẻ bằng phím Enter/Space cho PC
        refs.flashcard.addEventListener("keydown", (event) => {
            if (event.key !== "Enter" && event.key !== " ") {
                return;
            }
            event.preventDefault();
            toggleFlashcard();
        });

        // 3. Các nút điều khiển giữ nguyên
        refs.prevBtn.addEventListener("click", () => stepCard(-1));
        refs.nextBtn.addEventListener("click", () => stepCard(1));
        refs.generateBtn.addEventListener("click", handleTopicGeneration);
        refs.explainGrammarBtn.addEventListener("click", handleExplainGrammar);
        
        refs.saveWordBtn.addEventListener("click", () => {
            const currentWord = getCurrentWord();
            if (!currentWord) {
                return;
            }
            toggleSavedWord(currentWord);
            updateSaveButton();
            renderSavedWords();
        });

        refs.topicInput.addEventListener("keydown", (event) => {
            if (event.key === "Enter" && !refs.generateBtn.disabled) {
                handleTopicGeneration();
            }
        });

        refs.savedWordsGrid.addEventListener("click", (event) => {
            const target = event.target.closest("[data-remove-saved-index]");
            if (!target) {
                return;
            }
            const index = Number(target.dataset.removeSavedIndex);
            if (Number.isNaN(index)) {
                return;
            }
            state.savedWordsList.splice(index, 1);
            persistSavedWords();
            renderSavedWords();
            updateSaveButton();
        });

        refs.clearSavedBtn.addEventListener("click", () => {
            if (!state.savedWordsList.length) {
                return;
            }
            if (!window.confirm("Bạn muốn xóa toàn bộ từ đã lưu chứ?")) {
                return;
            }
            state.savedWordsList = [];
            persistSavedWords();
            renderSavedWords();
            updateSaveButton();
        });

        renderTopics();
        renderSavedWords();
        const topics = Object.keys(state.appData);
        if (topics.length) {
            loadTopic(topics[0]);
        } else {
            showCard();
        }
    }

// ---- src/70-reading.js ----
    function renderReadingContent(content) {
        clearNode(refs.readingContent);
        const tokens = content.split(/\s+/).filter(Boolean);

        tokens.forEach((token, index) => {
            const wordButton = createElement("span", "", token);
            wordButton.dataset.word = normalizeLookupKey(token);
            refs.readingContent.appendChild(wordButton);

            if (index < tokens.length - 1) {
                refs.readingContent.appendChild(document.createTextNode(" "));
            }
        });
    }

    function showTooltipForWord(target) {
        const lookupKey = target.dataset.word || normalizeLookupKey(target.textContent);
        const meaning = state.currentReadingVocab[lookupKey] || "Chưa có nghĩa cho từ này.";
        refs.tooltip.textContent = meaning;
        show(refs.tooltip);

        requestAnimationFrame(() => {
            const rect = target.getBoundingClientRect();
            refs.tooltip.style.left = `${window.scrollX + rect.left + (rect.width / 2) - (refs.tooltip.offsetWidth / 2)}px`;
            refs.tooltip.style.top = `${window.scrollY + rect.top - refs.tooltip.offsetHeight - 12}px`;
        });
    }

    async function handleReadingGeneration() {
        setBusy(refs.generateReadingBtn, true, "Đang tạo...");
        show(refs.readingLoadingMsg);
        hide(refs.readingBox);
        hide(refs.fullTranslationBox);

        try {
            const data = await api.generateReading(refs.levelSelect.value);
            state.currentReadingVocab = data.vocab || {};
            refs.readingTitle.textContent = data.title;
            refs.fullTranslationBox.textContent = data.translation;
            refs.toggleTranslationBtn.textContent = "Xem bản dịch đầy đủ";
            renderReadingContent(data.content);
            show(refs.readingBox);
        } catch (error) {
            showError(error.message);
        } finally {
            setBusy(refs.generateReadingBtn, false, "Đang tạo...");
            hide(refs.readingLoadingMsg);
        }
    }

    function initReading() {
        refs.generateReadingBtn.addEventListener("click", handleReadingGeneration);

        refs.readingContent.addEventListener("click", (event) => {
            const target = event.target.closest("span[data-word]");
            if (!target) {
                return;
            }
            showTooltipForWord(target);
        });

        refs.toggleTranslationBtn.addEventListener("click", () => {
            refs.fullTranslationBox.classList.toggle("hidden");
            refs.toggleTranslationBtn.textContent = refs.fullTranslationBox.classList.contains("hidden")
                ? "Xem bản dịch đầy đủ"
                : "Ẩn bản dịch";
        });

        document.addEventListener("click", (event) => {
            if (!event.target.closest("#readingContent span")) {
                hide(refs.tooltip);
            }
        });
    }

// ---- src/80-grammar.js ----
    async function handleGrammarGeneration() {
        setBusy(refs.generateGrammarBtn, true, "Đang lấy...");
        show(refs.grammarLoadingMsg);
        hide(refs.grammarBox);

        try {
            const data = await api.generateGrammar(refs.grammarSelect.value);
            refs.grammarTitle.textContent = data.title;
            refs.grammarFormula.textContent = data.formula;
            refs.grammarUsage.textContent = data.usage;

            clearNode(refs.grammarExamples);
            data.examples.forEach((example) => {
                refs.grammarExamples.appendChild(createElement("li", "", example));
            });

            show(refs.grammarBox);
        } catch (error) {
            showError(error.message);
        } finally {
            setBusy(refs.generateGrammarBtn, false, "Đang lấy...");
            hide(refs.grammarLoadingMsg);
        }
    }

    function initGrammar() {
        refs.generateGrammarBtn.addEventListener("click", handleGrammarGeneration);
    }

// ---- src/90-chat.js ----
    function appendChatMessage(sender, text) {
        const wrapper = createElement("div", `message ${sender}-message`);
        const bubble = createElement("div", "msg-bubble", text);
        wrapper.appendChild(bubble);
        refs.chatBox.appendChild(wrapper);
        refs.chatBox.scrollTop = refs.chatBox.scrollHeight;
        return wrapper;
    }

    function appendTypingIndicator() {
        const wrapper = createElement("div", "message ai-message");
        const bubble = createElement("div", "typing-indicator");
        bubble.appendChild(createElement("span"));
        bubble.appendChild(createElement("span"));
        bubble.appendChild(createElement("span"));
        wrapper.appendChild(bubble);
        refs.chatBox.appendChild(wrapper);
        refs.chatBox.scrollTop = refs.chatBox.scrollHeight;
        return wrapper;
    }

    async function handleChatSend() {
        const text = refs.chatInput.value.trim();
        if (!text) {
            return;
        }

        state.chatHistory.push({ role: "user", content: text });
        appendChatMessage("user", text);
        refs.chatInput.value = "";
        refs.chatInput.disabled = true;
        refs.sendChatBtn.disabled = true;

        const typingIndicator = appendTypingIndicator();

        try {
            const data = await api.chat(state.chatHistory);
            typingIndicator.remove();
            appendChatMessage("ai", data.message);
            state.chatHistory.push({ role: "assistant", content: data.message });
            if (state.chatHistory.length > 12) {
                state.chatHistory = state.chatHistory.slice(-12);
            }
        } catch (error) {
            typingIndicator.remove();
            appendChatMessage("ai", error.message);
        } finally {
            refs.chatInput.disabled = false;
            refs.sendChatBtn.disabled = false;
            refs.chatInput.focus();
        }
    }

    function initChat() {
        refs.sendChatBtn.addEventListener("click", handleChatSend);
        refs.chatInput.addEventListener("keydown", (event) => {
            if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                handleChatSend();
            }
        });
    }

// ---- src/100-listening.js ----
    function renderListeningQuestions() {
        clearNode(refs.quizContainer);

        state.currentListening.questions.forEach((question, questionIndex) => {
            const card = createElement("article", "quiz-card");
            const heading = createElement("h4", "", `Câu ${questionIndex + 1}: ${question.q}`);
            card.appendChild(heading);

            question.options.forEach((option, optionIndex) => {
                const label = createElement("label", "quiz-option-label");
                const input = document.createElement("input");
                input.type = "radio";
                input.name = `question-${questionIndex}`;
                input.value = String(optionIndex);

                label.appendChild(input);
                label.appendChild(document.createTextNode(` ${option}`));
                card.appendChild(label);
            });

            refs.quizContainer.appendChild(card);
        });
    }

    function buildUtterance(transcript, level) {
        if (!window.speechSynthesis) {
            return null;
        }
        const utterance = new SpeechSynthesisUtterance(transcript);
        utterance.lang = "en-US";
        utterance.rate = level === "easy" ? 0.82 : level === "medium" ? 0.95 : 1.04;
        return utterance;
    }

    async function handleListeningGeneration() {
        setBusy(refs.generateListenBtn, true, "Đang tạo...");
        show(refs.listenLoadingMsg);
        hide(refs.listeningBox);
        hide(refs.quizResult);
        hide(refs.showTranscriptBtn);
        hide(refs.transcriptBox);
        refs.submitQuizBtn.disabled = false;

        if (window.speechSynthesis) {
            window.speechSynthesis.cancel();
        }

        try {
            const level = refs.listenLevelSelect.value;
            const data = await api.generateListening(level);
            state.currentListening.transcript = data.transcript;
            state.currentListening.questions = data.questions;
            state.currentListening.utterance = buildUtterance(data.transcript, level);

            refs.transcriptBox.textContent = data.transcript;
            renderListeningQuestions();
            show(refs.listeningBox);
        } catch (error) {
            showError(error.message);
        } finally {
            setBusy(refs.generateListenBtn, false, "Đang tạo...");
            hide(refs.listenLoadingMsg);
        }
    }

    function handleSubmitQuiz() {
        if (!state.currentListening.questions.length) {
            return;
        }

        let score = 0;
        state.currentListening.questions.forEach((question, questionIndex) => {
            const checked = refs.quizContainer.querySelector(`input[name="question-${questionIndex}"]:checked`);
            const options = refs.quizContainer.querySelectorAll(`input[name="question-${questionIndex}"]`);

            options.forEach((input, optionIndex) => {
                const label = input.closest(".quiz-option-label");
                label.classList.remove("option-correct", "option-wrong");
                if (optionIndex === question.answerIndex) {
                    label.classList.add("option-correct");
                }
                if (checked && Number(checked.value) === optionIndex && optionIndex !== question.answerIndex) {
                    label.classList.add("option-wrong");
                }
            });

            if (checked && Number(checked.value) === question.answerIndex) {
                score += 1;
            }
        });

        refs.quizResult.textContent = `Bạn đúng ${score} / ${state.currentListening.questions.length} câu.`;
        refs.quizResult.style.background = score === state.currentListening.questions.length
            ? "rgba(30, 143, 98, 0.14)"
            : "rgba(212, 138, 18, 0.18)";
        refs.quizResult.style.color = score === state.currentListening.questions.length ? "#116241" : "#8e5d09";
        show(refs.quizResult);
        show(refs.showTranscriptBtn);
        refs.submitQuizBtn.disabled = true;
    }

    function handlePlayAudio() {
        if (!state.currentListening.utterance || !window.speechSynthesis) {
            showError("Chưa có đoạn nghe để phát.");
            return;
        }

        if (window.speechSynthesis.paused) {
            window.speechSynthesis.resume();
            return;
        }

        window.speechSynthesis.cancel();
        window.speechSynthesis.speak(state.currentListening.utterance);
    }

    function initListening() {
        refs.generateListenBtn.addEventListener("click", handleListeningGeneration);
        refs.submitQuizBtn.addEventListener("click", handleSubmitQuiz);
        refs.playAudioBtn.addEventListener("click", handlePlayAudio);
        refs.pauseAudioBtn.addEventListener("click", () => {
            if (window.speechSynthesis) {
                window.speechSynthesis.pause();
            }
        });
        refs.stopAudioBtn.addEventListener("click", () => {
            if (window.speechSynthesis) {
                window.speechSynthesis.cancel();
            }
        });
        refs.showTranscriptBtn.addEventListener("click", () => {
            refs.transcriptBox.classList.toggle("hidden");
            refs.showTranscriptBtn.textContent = refs.transcriptBox.classList.contains("hidden")
                ? "Xem lời thoại"
                : "Ẩn lời thoại";
        });
    }

// ---- src/110-matching.js ----
    function updateMatchingProgress() {
        refs.matchingProgressText.textContent = `${state.matching.matchedIds.size} / ${state.matching.pairs.length} cặp đúng`;
    }

    function setMatchingFeedback(message, type) {
        refs.matchingFeedback.textContent = message;
        refs.matchingFeedback.classList.remove("success", "error");
        if (type === "success" || type === "error") {
            refs.matchingFeedback.classList.add(type);
        }
    }

    function getPairById(pairId) {
        return state.matching.pairs.find((pair) => pair.id === pairId) || null;
    }

    function renderMatchingColumn(container, side, order) {
        clearNode(container);

        order.forEach((pairId) => {
            const pair = getPairById(pairId);
            if (!pair) {
                return;
            }

            const button = createElement("button", "matching-option", side === "en" ? pair.en : pair.vi);
            button.type = "button";
            button.dataset.side = side;
            button.dataset.id = String(pair.id);

            if (state.matching.selected[side] === pair.id) {
                button.classList.add("is-selected");
            }
            if (state.matching.matchedIds.has(pair.id)) {
                button.classList.add("is-matched");
                button.disabled = true;
            }

            container.appendChild(button);
        });
    }

    function renderMatchingBoard() {
        if (!state.matching.pairs.length) {
            hide(refs.matchingBox);
            return;
        }

        renderMatchingColumn(refs.matchingEnList, "en", state.matching.enOrder);
        renderMatchingColumn(refs.matchingViList, "vi", state.matching.viOrder);
        updateMatchingProgress();
        show(refs.matchingBox);
    }

    function evaluateMatchingSelection() {
        const selectedEnglish = state.matching.selected.en;
        const selectedVietnamese = state.matching.selected.vi;

        if (!selectedEnglish || !selectedVietnamese) {
            return;
        }

        if (selectedEnglish === selectedVietnamese) {
            const pair = getPairById(selectedEnglish);
            state.matching.matchedIds.add(selectedEnglish);
            state.matching.selected = { en: null, vi: null };
            renderMatchingBoard();

            if (state.matching.matchedIds.size === state.matching.pairs.length) {
                setMatchingFeedback("Hoàn thành rồi. Bạn đã ghép đúng toàn bộ bộ từ.", "success");
            } else {
                setMatchingFeedback(`Chính xác: ${pair.en} = ${pair.vi}`, "success");
            }
            return;
        }

        const wrongEnglish = getPairById(selectedEnglish);
        const wrongVietnamese = getPairById(selectedVietnamese);
        state.matching.selected = { en: null, vi: null };
        renderMatchingBoard();
        setMatchingFeedback(
            `Chưa đúng: "${wrongEnglish?.en || "từ"}" chưa ghép với "${wrongVietnamese?.vi || "nghĩa"}".`,
            "error",
        );
    }

    function handleMatchingPick(side, pairId) {
        if (state.matching.matchedIds.has(pairId)) {
            return;
        }

        state.matching.selected[side] = state.matching.selected[side] === pairId ? null : pairId;
        renderMatchingBoard();
        evaluateMatchingSelection();
    }

    function seedMatchingBoard(pairs, source) {
        state.matching.pairs = pairs;
        state.matching.enOrder = shuffle(pairs.map((pair) => pair.id));
        state.matching.viOrder = shuffle(pairs.map((pair) => pair.id));
        state.matching.matchedIds = new Set();
        state.matching.selected = { en: null, vi: null };
        state.matching.lastSource = source;

        renderMatchingBoard();
        if (source === "fallback") {
            setMatchingFeedback("AI chưa bật nên đang dùng bộ ghép từ an toàn có sẵn.", "");
        } else {
            setMatchingFeedback("Bộ ghép từ AI đã sẵn sàng. Chọn 1 từ tiếng Anh và 1 nghĩa tiếng Việt.", "");
        }
    }

    async function handleMatchingGeneration() {
        setBusy(refs.generateMatchingBtn, true, "Đang tạo...");
        show(refs.matchingLoadingMsg);

        try {
            const level = refs.matchingLevelSelect.value;
            state.matching.level = level;
            const data = await api.generateMatching(level);
            seedMatchingBoard(Array.isArray(data.pairs) ? data.pairs : [], data.source);
        } catch (error) {
            showError(error.message);
        } finally {
            setBusy(refs.generateMatchingBtn, false, "Đang tạo...");
            hide(refs.matchingLoadingMsg);
        }
    }

    function initMatching() {
        refs.generateMatchingBtn.addEventListener("click", handleMatchingGeneration);
        refs.resetMatchingBtn.addEventListener("click", () => {
            if (!state.matching.pairs.length) {
                return;
            }
            state.matching.enOrder = shuffle(state.matching.enOrder);
            state.matching.viOrder = shuffle(state.matching.viOrder);
            state.matching.selected = { en: null, vi: null };
            renderMatchingBoard();
            setMatchingFeedback("Đã trộn lại các lựa chọn.", "");
        });

        refs.matchingEnList.addEventListener("click", (event) => {
            const target = event.target.closest("button[data-side='en']");
            if (!target) {
                return;
            }
            handleMatchingPick("en", Number(target.dataset.id));
        });

        refs.matchingViList.addEventListener("click", (event) => {
            const target = event.target.closest("button[data-side='vi']");
            if (!target) {
                return;
            }
            handleMatchingPick("vi", Number(target.dataset.id));
        });
    }

// ---- src/120-bootstrap.js ----
function updateStatusBanner(message, warning) {
        // Chặn lỗi: Nếu đại ca đã xóa thẻ banner ở HTML thì code sẽ tự dừng, không báo lỗi đỏ màn hình
        if (!refs.appStatusBanner) return; 

        refs.appStatusBanner.textContent = message;
        refs.appStatusBanner.classList.toggle("warning", Boolean(warning));
    }

    function syncStrictAiButtons() {
        refs.strictAiButtons.forEach((button) => {
            button.disabled = !state.bootstrap.aiEnabled;
            button.title = state.bootstrap.aiEnabled
                ? ""
                // Sửa câu thông báo khi di chuột vào nút bị khóa thành văn phong lịch sự
                : "Tính năng Trợ lý AI hiện đang bảo trì hoặc chưa khả dụng. Vui lòng thử lại sau."; 
        });
    }

    async function initBootstrapStatus() {
        try {
            const bootstrap = await api.getBootstrap();
            state.bootstrap = bootstrap;

            if (bootstrap.aiEnabled) {
                // Câu thông báo thương mại, tri thức (hoặc nó sẽ ẩn luôn nếu đại ca đã xóa banner)
                updateStatusBanner("Hệ thống ZeroEnglish đã kết nối. Trợ lý AI học thuật sẵn sàng.", false);
            } else {
                // Sửa thông báo lỗi mất key AI
                updateStatusBanner("Hệ thống AI đang bảo trì. Các tính năng luyện tập tiêu chuẩn vẫn hoạt động bình thường.", true);
            }
        } catch (error) {
            // Sửa thông báo khi web bị mất kết nối hoàn toàn
            updateStatusBanner("Không thể kết nối đến máy chủ học thuật. Vui lòng kiểm tra lại đường truyền internet của bạn.", true);
        } finally {
            syncStrictAiButtons();
        }
    }

    function initApp() {
        initTabs();
        initFlashcards();
        initReading();
        initGrammar();
        initChat();
        initListening();
        initMatching();
        initBootstrapStatus();

        window.addEventListener("beforeunload", () => {
            if (window.speechSynthesis) {
                window.speechSynthesis.cancel();
            }
        });
    }

    initApp();

// ---- src/999-end.js ----
})();
