    const refs = {
        // ── App status ──────────────────────────────────────────
        appStatusBanner: document.getElementById("appStatusBanner"),
        strictAiButtons: Array.from(document.querySelectorAll('[data-ai-required="strict"]')),
        tabButtons: Array.from(document.querySelectorAll(".tab-btn")),
        views: Array.from(document.querySelectorAll(".view-section")),
        // ── English Flashcard ────────────────────────────────────
        topicInput: document.getElementById("topicInput"),
        generateBtn: document.getElementById("generateBtn"),
        loadingMsg: document.getElementById("loadingMsg"),
        topicList: document.getElementById("topicList"),
        currentTopicTitle: document.getElementById("currentTopicTitle"),
        progressText: document.getElementById("progressText"),
        cardContainer: document.getElementById("cardContainer"),
        flashcard: document.getElementById("flashcard"),
        wordEn: document.getElementById("wordEn"),
        wordPro: document.getElementById("wordPro"),
        wordVi: document.getElementById("wordVi"),
        wordEx: document.getElementById("wordEx"),
        actionButtons: document.getElementById("actionButtons"),
        saveWordBtn: document.getElementById("saveWordBtn"),
        explainGrammarBtn: document.getElementById("explainGrammarBtn"),
        explanationBox: document.getElementById("explanationBox"),
        explanationText: document.getElementById("explanationText"),
        controls: document.getElementById("controls"),
        prevBtn: document.getElementById("prevBtn"),
        nextBtn: document.getElementById("nextBtn"),
        flashcardPlaceholder: document.getElementById("flashcardPlaceholder"),
        flashcardHeader: document.getElementById("flashcardHeader"),
        // ── English Reading ──────────────────────────────────────
        levelSelect: document.getElementById("levelSelect"),
        generateReadingBtn: document.getElementById("generateReadingBtn"),
        readingLoadingMsg: document.getElementById("readingLoadingMsg"),
        readingBox: document.getElementById("readingBox"),
        readingTitle: document.getElementById("readingTitle"),
        readingContent: document.getElementById("readingContent"),
        toggleTranslationBtn: document.getElementById("toggleTranslationBtn"),
        fullTranslationBox: document.getElementById("fullTranslationBox"),
        tooltip: document.getElementById("tooltip"),
        // ── English Grammar ──────────────────────────────────────
        grammarSelect: document.getElementById("grammarSelect"),
        generateGrammarBtn: document.getElementById("generateGrammarBtn"),
        grammarLoadingMsg: document.getElementById("grammarLoadingMsg"),
        grammarBox: document.getElementById("grammarBox"),
        grammarTitle: document.getElementById("grammarTitle"),
        grammarFormula: document.getElementById("grammarFormula"),
        grammarUsage: document.getElementById("grammarUsage"),
        grammarExamples: document.getElementById("grammarExamples"),
        // ── English Chat ─────────────────────────────────────────
        chatBox: document.getElementById("chatBox"),
        chatInput: document.getElementById("chatInput"),
        sendChatBtn: document.getElementById("sendChatBtn"),
        // ── English Listening ────────────────────────────────────
        listenLevelSelect: document.getElementById("listenLevelSelect"),
        generateListenBtn: document.getElementById("generateListenBtn"),
        listenLoadingMsg: document.getElementById("listenLoadingMsg"),
        listeningBox: document.getElementById("listeningBox"),
        playAudioBtn: document.getElementById("playAudioBtn"),
        pauseAudioBtn: document.getElementById("pauseAudioBtn"),
        stopAudioBtn: document.getElementById("stopAudioBtn"),
        quizContainer: document.getElementById("quizContainer"),
        submitQuizBtn: document.getElementById("submitQuizBtn"),
        showTranscriptBtn: document.getElementById("showTranscriptBtn"),
        quizResult: document.getElementById("quizResult"),
        transcriptBox: document.getElementById("transcriptBox"),
        // ── English Matching ─────────────────────────────────────
        matchingLevelSelect: document.getElementById("matchingLevelSelect"),
        generateMatchingBtn: document.getElementById("generateMatchingBtn"),
        matchingLoadingMsg: document.getElementById("matchingLoadingMsg"),
        matchingBox: document.getElementById("matchingBox"),
        matchingProgressText: document.getElementById("matchingProgressText"),
        resetMatchingBtn: document.getElementById("resetMatchingBtn"),
        matchingEnList: document.getElementById("matchingEnList"),
        matchingViList: document.getElementById("matchingViList"),
        matchingFeedback: document.getElementById("matchingFeedback"),
        // ── English Saved ────────────────────────────────────────
        clearSavedBtn: document.getElementById("clearSavedBtn"),
        savedWordsGrid: document.getElementById("savedWordsGrid"),
        // ── Chinese Flashcard ────────────────────────────────────
        cnTopicInput: document.getElementById("cnTopicInput"),
        cnGenerateBtn: document.getElementById("cnGenerateBtn"),
        cnLoadingMsg: document.getElementById("cnLoadingMsg"),
        cnTopicList: document.getElementById("cnTopicList"),
        cnCurrentTopicTitle: document.getElementById("cnCurrentTopicTitle"),
        cnProgressText: document.getElementById("cnProgressText"),
        cnCardContainer: document.getElementById("cnCardContainer"),
        cnFlashcard: document.getElementById("cnFlashcard"),
        cnWordZh: document.getElementById("cnWordZh"),
        cnWordPro: document.getElementById("cnWordPro"),
        cnWordVi: document.getElementById("cnWordVi"),
        cnWordEx: document.getElementById("cnWordEx"),
        cnActionButtons: document.getElementById("cnActionButtons"),
        cnSaveWordBtn: document.getElementById("cnSaveWordBtn"),
        cnExplainBtn: document.getElementById("cnExplainBtn"),
        cnExplanationBox: document.getElementById("cnExplanationBox"),
        cnExplanationText: document.getElementById("cnExplanationText"),
        cnControls: document.getElementById("cnControls"),
        cnPrevBtn: document.getElementById("cnPrevBtn"),
        cnNextBtn: document.getElementById("cnNextBtn"),
        cnFlashcardPlaceholder: document.getElementById("cnFlashcardPlaceholder"),
        cnFlashcardHeader: document.getElementById("cnFlashcardHeader"),
        // ── Chinese Reading ──────────────────────────────────────
        cnLevelSelect: document.getElementById("cnLevelSelect"),
        cnGenerateReadingBtn: document.getElementById("cnGenerateReadingBtn"),
        cnReadingLoadingMsg: document.getElementById("cnReadingLoadingMsg"),
        cnReadingBox: document.getElementById("cnReadingBox"),
        cnReadingTitle: document.getElementById("cnReadingTitle"),
        cnReadingContent: document.getElementById("cnReadingContent"),
        cnToggleTranslationBtn: document.getElementById("cnToggleTranslationBtn"),
        cnFullTranslationBox: document.getElementById("cnFullTranslationBox"),
        // ── Chinese Listening ────────────────────────────────────
        cnListenLevelSelect: document.getElementById("cnListenLevelSelect"),
        cnGenerateListenBtn: document.getElementById("cnGenerateListenBtn"),
        cnListenLoadingMsg: document.getElementById("cnListenLoadingMsg"),
        cnListeningBox: document.getElementById("cnListeningBox"),
        cnPlayAudioBtn: document.getElementById("cnPlayAudioBtn"),
        cnStopAudioBtn: document.getElementById("cnStopAudioBtn"),
        cnQuizContainer: document.getElementById("cnQuizContainer"),
        cnSubmitQuizBtn: document.getElementById("cnSubmitQuizBtn"),
        cnShowTranscriptBtn: document.getElementById("cnShowTranscriptBtn"),
        cnQuizResult: document.getElementById("cnQuizResult"),
        cnTranscriptBox: document.getElementById("cnTranscriptBox"),
        // ── Chinese Matching ─────────────────────────────────────
        cnMatchingLevelSelect: document.getElementById("cnMatchingLevelSelect"),
        cnGenerateMatchingBtn: document.getElementById("cnGenerateMatchingBtn"),
        cnMatchingLoadingMsg: document.getElementById("cnMatchingLoadingMsg"),
        cnMatchingBox: document.getElementById("cnMatchingBox"),
        cnMatchingProgressText: document.getElementById("cnMatchingProgressText"),
        cnResetMatchingBtn: document.getElementById("cnResetMatchingBtn"),
        cnMatchingZhList: document.getElementById("cnMatchingZhList"),
        cnMatchingViList: document.getElementById("cnMatchingViList"),
        cnMatchingFeedback: document.getElementById("cnMatchingFeedback"),
        // ── Chinese Saved ────────────────────────────────────────
        cnClearSavedBtn: document.getElementById("cnClearSavedBtn"),
        cnSavedWordsGrid: document.getElementById("cnSavedWordsGrid"),
    };
